### ISSUE TITLE
Tries to clone something it shouldn't

### ISSUE THREAD

**Issue by vemv** [reifyhealth/lein-git-down#20]
Hi there again,

given a project using lein-git-down 0.3.1, if I place the following in my ~/.lein/profiles.clj:

```
{:user {:dependencies [[nrepl-debugger "0.1.0-SNAPSHOT"]] ...
```

...whenever I `lein repl`, the following will be printed:

```
Cloning: https://github.com/nrepl-debugger/nrepl-debugger
```

It doesn't seem to affect anything (including startup time), but it might signal some issue.

Thanks - Victor

**Comment by vemv** [comment]
Worth noting, `https://github.com/nrepl-debugger/nrepl-debugger` does not exist - it's lein-git-down who tried to infer that

**Comment by manderson202** [comment]
Since we have created a custom Maven Wagon to interact with GitHub it works with the standard workflow for resolving dependencies. This means that if you have a repository configured to use the Git Wagon (eg: `:repositories [["public-github" {:url "git://github.com"}]]`) then it will be used to try and resolve the artifact if it can't be found in any other repository. I'm assuming the library in your user profile is not in Maven Central, Clojars, or any other repo defined in your `project.clj` so the next one that gets checked is the "public-github" (which I'm assuming you have configured). The same thing would happen if you defined a private Nexus repo or used the S3 Wagon to pull from a private S3 bucket, etc. So, in short, this is the intended behavior.

Let me know if you feel there is something else going on, but other than the "Cloning..." log line (which comes from GitLibs), it shouldn't negatively impact your build.

**Comment by vemv** [comment]
Hi,

thanks for the clarification!

Yes, I suspected this behavior was simply analog to the other wagons.

OTOH, it's a bit unsettling, especially for newcomers, to see an extraneous repo supposedly being cloned. It kind of feels like a security risk (what if the repo _does_ exist but it's a unrelated one), even assuming that no cloning can possibly happen.

I would suggest:

* Silence that specific GitLibs output, e.g. wrap it `with-out-str` and remove it
* Optionally, replace this line with something more reassuring, e.g. `Checking if https://github.com/nrepl-debugger/nrepl-debugger at 4505f780078a00f52 exists...`

**Comment by manderson202** [comment]
Thanks for the feedback. I agree the UX here could be improved. I'm going to keep this open to look into more when I have some time. Been tied up with some other work lately, but do plan to get back to this and the other open issue. Appreciate the thoughtful comments!
